services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    env_file:
      - docker.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  pgdata:

networks:
  postgres:
    driver: bridge